# Generated by Django 5.1 on 2024-08-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkinput',
            name='milk_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
